--BORRAR

DROP TABLE RESTAURANTE CASCADE CONSTRAINTS;
DROP TABLE REPRESENTANTE CASCADE CONSTRAINTS;
DROP TABLE INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOSBODEGA CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_INGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE CLIENTESREGISTRADOS CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE EQUIVALENCIASINGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_MENU CASCADE CONSTRAINTS;
DROP TABLE RESTAURANTE_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE RESTAURANTE_INGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE EQUIVALENCIASPRODUCTO CASCADE CONSTRAINTS;
DROP TABLE TIPOCOMIDA CASCADE CONSTRAINTS;
DROP TABLE ZONA CASCADE CONSTRAINTS;
DROP TABLE CHECKOUT CASCADE CONSTRAINTS;
DROP TABLE EVENTO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_CHECKOUT CASCADE CONSTRAINTS;
DROP TABLE MENU_CHECKOUT CASCADE CONSTRAINTS;

--CREAR

CREATE TABLE RESTAURANTE(
    NOMBRE VARCHAR(35),
    DESCRIPCION VARCHAR(280),
    TIPOCOMIDAREST VARCHAR(15),
    PAGINAWEB VARCHAR(50),
    CONSTRAINT nom_rest_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT rest_ck_desc CHECK (LENGTH(DESCRIPCION) > 5),
    CONSTRAINT rest_ck_pag CHECK ( LENGTH(PAGINAWEB)> 5),
    CONSTRAINT rest_ck_nomb CHECK ( LENGTH(NOMBRE)> 5));
    
CREATE TABLE INVENTARIO(
    RESTAURANTE_NOMBRE VARCHAR2(35),
    CONSTRAINT inv_nom_pk PRIMARY KEY(RESTAURANTE_NOMBRE),
    CONSTRAINT inv_nom_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));

    
CREATE TABLE PRODUCTO(
    NOMBRE VARCHAR2(25),
    CATEGORIA NUMBER(8),
    PRECIOVENTA NUMBER(18),
    COSTOPRODUCCION NUMBER(17),
    TIPOCOMIDAPROD VARCHAR2(20),
    TIEMPOPREPARACION NUMBER(7),
    CONSTRAINT pro_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT pro_ck_nom CHECK ( LENGTH(NOMBRE)> 5),
    CONSTRAINT pro_ck_cat CHECK ( CATEGORIA > 0),
    CONSTRAINT pro_ck_precVent CHECK ( PRECIOVENTA > 0),
    CONSTRAINT pro_ck_costProd CHECK ( COSTOPRODUCCION < PRECIOVENTA),
    CONSTRAINT pro_ck_tipocomprod CHECK ( LENGTH(TIPOCOMIDAPROD) > 0),
    CONSTRAINT pro_ck_tiempoPrep CHECK ( TIEMPOPREPARACION > 0));

CREATE TABLE PRODUCTOSBODEGA(
    CANTIDADPRODUCTO NUMBER(10),
    INVENTARIO_RESTAURANTE_NOMBRE VARCHAR2(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    MAXIMO NUMBER(10),
    CONSTRAINT prodbod_pk PRIMARY KEY(INVENTARIO_RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT prodbod_inv_fk
        FOREIGN KEY (INVENTARIO_RESTAURANTE_NOMBRE)
        REFERENCES INVENTARIO(RESTAURANTE_NOMBRE),
    CONSTRAINT prodbod_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT prodBod_ck_cantProd CHECK ( CANTIDADPRODUCTO >= 0 AND MAXIMO>0 AND CANTIDADPRODUCTO<=MAXIMO));

CREATE TABLE EQUIVALENCIASPRODUCTO(
    RESTAURANTE_NOMBRE VARCHAR2(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    EQUIVALENCIA NUMBER(8),
    CONSTRAINT eqPROD_PK PRIMARY KEY (RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT EQPROD_PROD_FK
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT EQPROD_REST_FK
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT EQPROD_EQUIV_CK
        CHECK (EQUIVALENCIA > 0));
    
CREATE TABLE INGREDIENTE(
    NOMBRE VARCHAR2(30),
    DESCESP VARCHAR2(300),
    DESCING VARCHAR2(300),
    TIPO VARCHAR(15),
    CONSTRAINT ing_PK PRIMARY KEY (NOMBRE),
    CONSTRAINT ing_ck_nom CHECK ( LENGTH(NOMBRE) > 0),
    CONSTRAINT ing_ck_descesp CHECK ( LENGTH(DESCESP) > 0),
    CONSTRAINT ing_ck_descing CHECK ( LENGTH(DESCING) > 0),
    CONSTRAINT ing_ck_tipo CHECK ( LENGTH(TIPO) > 0));
        
CREATE TABLE PRODUCTO_INGREDIENTE(
    INGREDIENTE_NOMBRE VARCHAR(30),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT proding_pk PRIMARY KEY (INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE),
    CONSTRAINT proding_ing_fk
        FOREIGN KEY (INGREDIENTE_NOMBRE)
        REFERENCES INGREDIENTE(NOMBRE),
    CONSTRAINT proding_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE) );
                     
CREATE TABLE EQUIVALENCIASINGREDIENTE(
    RESTAURANTE_NOMBRE VARCHAR(35),
    INGREDIENTE_NOMBRE VARCHAR2(30),
    EQUIVALENCIA NUMBER(8),
    CONSTRAINT EQINGR_PK PRIMARY KEY (RESTAURANTE_NOMBRE, INGREDIENTE_NOMBRE),
    CONSTRAINT EQINGR_INGR_FK
        FOREIGN KEY (INGREDIENTE_NOMBRE)
        REFERENCES INGREDIENTE(NOMBRE),
    CONSTRAINT EQINGR_REST_FK
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT EQINGR_EQUIV_CK CHECK (EQUIVALENCIA >0)
        );
        

CREATE TABLE MENU(
    NOMBRE VARCHAR2(25),
    CATEGORIA NUMBER(8),
    PRECIOVENTA NUMBER(18),
    COSTOPRODUCCION NUMBER(17),
    TIPOCOMIDAPROD VARCHAR2(20),
    TIEMPOPREPARACION NUMBER(7),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT menu_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT menu_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT men_ck_nom CHECK ( LENGTH(NOMBRE)> 5),
    CONSTRAINT men_ck_cat CHECK ( CATEGORIA > 0),
    CONSTRAINT men_ck_precVent CHECK ( PRECIOVENTA > 0),
    CONSTRAINT men_ck_costProd CHECK ( COSTOPRODUCCION > 0),
    CONSTRAINT men_ck_tipocomprod CHECK ( LENGTH(TIPOCOMIDAPROD) > 0),
    CONSTRAINT men_ck_tiempoPrep CHECK ( TIEMPOPREPARACION > 0));
    
CREATE TABLE USUARIO(
    USUARIO VARCHAR(30),
    CONTRASENA VARCHAR(30),
    ROL VARCHAR(30),
    CORREO VARCHAR(40),
    CONSTRAINT usr_pk PRIMARY KEY (USUARIO),
    CONSTRAINT usr_ck_usr CHECK ( LENGTH(USUARIO) > 3),
    CONSTRAINT usr_ck_cntrs CHECK ( LENGTH(CONTRASENA) > 5),
    CONSTRAINT usr_ck_rol CHECK ( LENGTH(ROL) > 3),
    CONSTRAINT usr_ck_correo CHECK ( LENGTH(CORREO) > 4));

CREATE TABLE CLIENTESREGISTRADOS(
    USUARIO_CLIENTE VARCHAR(30),
    CONSTRAINT CLI_pk PRIMARY KEY (USUARIO_CLIENTE),
    CONSTRAINT cli_usr_fk 
        FOREIGN KEY (USUARIO_CLIENTE)
        REFERENCES USUARIO(USUARIO));
    
CREATE TABLE ZONA(
    NOMBRE VARCHAR(30),
    CAPACIDAD NUMBER(8),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT zona_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT zona_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT zona_ck_nom CHECK (LENGTH(NOMBRE) > 3),
    CONSTRAINT zona_ck_cap CHECK ( CAPACIDAD > 0));

CREATE TABLE EVENTO(
    ID NUMBER(30),
    MENU_NOMBRE VARCHAR(25),
    CLIREGS_USUARIO_CLIENTE VARCHAR(30),
    ZONA_NOMBRE VARCHAR(30),
    CONSTRAINT evento_pk PRIMARY KEY (ID),
    CONSTRAINT evento_menu_fk
        FOREIGN KEY(MENU_NOMBRE)
        REFERENCES MENU(NOMBRE),
    CONSTRAINT evento_cli_fk
        FOREIGN KEY(CLIREGS_USUARIO_CLIENTE)
        REFERENCES CLIENTESREGISTRADOS(USUARIO_CLIENTE),
    CONSTRAINT evento_zon_fk
        FOREIGN KEY(ZONA_NOMBRE)
        REFERENCES ZONA(NOMBRE),
    CONSTRAINT evento_ck_id CHECK (ID > 0));
        
CREATE TABLE RESTAURANTE_PRODUCTO(
    RESTAURANTE_NOMBRE VARCHAR(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT rest_prod_pk PRIMARY KEY (RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT rest_prod_rest_fk
        FOREIGN KEY(RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT rest_prod_PROD_fk
        FOREIGN KEY(PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE));
        
CREATE TABLE RESTAURANTE_INGREDIENTE(
    RESTAURANTE_NOMBRE VARCHAR(35),
    INGREDIENTE_NOMBRE VARCHAR(30),
    CONSTRAINT rest_ingr_pk PRIMARY KEY (RESTAURANTE_NOMBRE,INGREDIENTE_NOMBRE),
    CONSTRAINT rest_ingr_rest_fk
        FOREIGN KEY(RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT rest_ingr_ingr_fk
        FOREIGN KEY(INGREDIENTE_NOMBRE)
        REFERENCES INGREDIENTE(NOMBRE));

CREATE TABLE PRODUCTO_MENU(
    MENU_NOMBRE VARCHAR(25),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT prod_menu_pk PRIMARY KEY (MENU_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT prod_menu_menu_fk
        FOREIGN KEY(MENU_NOMBRE)
        REFERENCES MENU(NOMBRE),
    CONSTRAINT prod_menu_prod_fk
        FOREIGN KEY(PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE));
        


    
CREATE TABLE TIPOCOMIDA(
    NOMBRE VARCHAR2(25),
    PRODUCTO_NOMBRE VARCHAR2(25),
    CONSTRAINT TIPOCOMIDA_pk PRIMARY KEY(NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT TIPOCOMIDA_PROD_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT tipocomida_ck_nombre CHECK (LENGTH(NOMBRE) > 0));



CREATE TABLE REPRESENTANTE(
    NOMBRE VARCHAR(30),
    CELULAR VARCHAR(10),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT rep_pk PRIMARY KEY(NOMBRE),
    CONSTRAINT rep_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT reprsnt_ck_nombre CHECK (LENGTH(NOMBRE) > 0),
    CONSTRAINT reprsnt_ck_celular CHECK (LENGTH(CELULAR) = 10)); -- El celular debe tenerlos 10 digitos

CREATE TABLE CHECKOUT(
    ID NUMBER(20),
    ENTREGADO NUMBER(1),
    TIEMPOR VARCHAR(15),
    ZONA_NOMBRE VARCHAR(30),
    CONSTRAINT checkout_pk PRIMARY KEY (ID),
    CONSTRAINT ck_zona_fk
        FOREIGN KEY (ZONA_NOMBRE)
        REFERENCES ZONA(NOMBRE),
    CONSTRAINT chkout_ck_id CHECK (ID > 0)
    --CONSTRAINT chkout_ck_tiempoR CHECK (TIEMPOR > 907427912000));--El tiempo entregado debe ser mayor a 1998 (o en particular, a la fecha de creacion de rotondandes)
    );

CREATE TABLE PRODUCTO_CHECKOUT(
    CHECKOUT_ID NUMBER(20),
    PRODUCTO_NOMBRE VARCHAR(25),
    CANTIDAD_PRODUCTO NUMBER(5),
    CONSTRAINT prod_ck_pk PRIMARY KEY(CHECKOUT_ID,PRODUCTO_NOMBRE),
    CONSTRAINT prod_ck_ck_fk
        FOREIGN KEY (CHECKOUT_ID)
        REFERENCES CHECKOUT(ID),
    CONSTRAINT prod_ck_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT prod_chk_ck CHECK (CANTIDAD_PRODUCTO>0));
    
    CREATE TABLE MENU_CHECKOUT(
    CHECKOUT_ID NUMBER(20),
    MENU_NOMBRE VARCHAR(25),
    CANTIDAD_PRODUCTO NUMBER(5),
    CONSTRAINT MENU_CHK_pk PRIMARY KEY(CHECKOUT_ID,MENU_NOMBRE),
    CONSTRAINT MENU_CHK_ck_fk
        FOREIGN KEY (CHECKOUT_ID)
        REFERENCES CHECKOUT(ID),
    CONSTRAINT MENU_CK_MENU_FK
        FOREIGN KEY (MENU_NOMBRE)
        REFERENCES MENU(NOMBRE),
    CONSTRAINT MENU_CHK_ck CHECK (CANTIDAD_PRODUCTO>0));
    
--POBLAR

INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CORRAL', 'HAMBURGUESAS EL CORRRAL, LA RECETA ORIGINAL', 'HAMBURGUESAS', 'http://elcorral.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CREPES Y WAFFLES', 'TORTILLAS DULCES Y SALDAS COLOMBIANAS', 'MIXTO', 'http://crepesandwaffles.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('RESTAURANTE DE LOS ALPES', 'RESTAURANTE MIXTO', 'MIXTO', 'http://restaurante.unialpes.blogspot.co');

INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Pepito P�rez', '6666666666', 'RESTAURANTE DE LOS ALPES');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Ana Lisa Melo', '0123456789', 'CORRAL');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Elver Galarga', '9876543210', 'CREPES Y WAFFLES');

INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CORRAL');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CREPES Y WAFFLES');


INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CORRALISIMA TODOTERRENO', 1, 20000, 10, 'HAMBURGUESA', 15 );
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('WAFFLE DE NUTELLA', 2, 17000, 3000, 'WAFFLE', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('HELADO DE VAINILLA', 2, 8000, 5000, 'ELAOU', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('MALTEADA DE VAINILLA', 3, 6000, 1000, 'BEBIDA', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('PAPAS FRITAS', 4, 4000, 3000, 'ACOMPAnAMIENTO', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CHURRASCO', 5, 3000, 500, 'PLATO FUERTE', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('GASEOSA', 3, 3000, 1000, 'BEBIDA',2);

INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'CHURRASCO');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (223, 'CREPES Y WAFFLES', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (223, 'CREPES Y WAFFLES', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'PAPAS FRITAS');

INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('RES', 'DE LA VACA', 'FROM THE COW', 'CARNE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAPA', 'DE LA TIERRA', 'FROM THE EARTH', 'PAPA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('WAFFLE', 'DE HARINA', 'FLOUR', 'WAFFLE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('NUTELLA', 'DE AVELLANAS', 'AVELLANEITON', 'SALSA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('AZUCAR', 'DE CAnA', 'FROM MATA', 'CANCER');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('HELADO DE VAINILLA', 'DE VAINILLA', 'FROM VACA', 'HELAO');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAN', 'DE TRIGO', 'WHEAT', 'PAN');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('LECHUGA', 'VEGANA', 'VEGAN', 'FITNESS');

INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('AZUCAR', 'GASEOSA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAPA', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAN', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('HELADO DE VAINILLA', 'MALTEADA DE VAINILLA');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('BOSQUE', 67, 'CREPES Y WAFFLES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('PLAYA BRISA Y MAR', 78, 'RESTAURANTE DE LOS ALPES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('GRANJA', 78, 'CORRAL');

INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (1, 1, 1501766720000, 'BOSQUE');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (2, 0, 1502371520000, 'PLAYA BRISA Y MAR');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (3, 1, 1499693120000, 'GRANJA');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (5, 1, 1499703406000, 'BOSQUE');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (4, 0, 1494436606000, 'PLAYA BRISA Y MAR');

INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (1, 'MALTEADA DE VAINILLA', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (2, 'CHURRASCO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'CORRALISIMA TODOTERRENO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'PAPAS FRITAS', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'GASEOSA', 3);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (4, 'CHURRASCO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (4, 'GASEOSA', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (5, 'WAFFLE DE NUTELLA', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (5, 'GASEOSA', 1);


INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('genericUser', 'Omaewamoushindeiru', 'cliente', 'abc@gmail.com');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('ottoman69', 'Nani?1234', 'cliente', 'gbravo@uniandes.edu.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('juan10', 'claveGenerica', 'admin restaurante', 'juan1650@hotmail.com');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('gbravo', '5 pa todos', 'cliente', 'gbravo@uniandes.edu.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('DB_MANAGER_rotonda', 'clavedificilysecreta', 'admin DB', 'db@rotondAndes.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('harryPotter', 'huerfanoxdxdxd', 'gerente', 'hp@howards.edu.xy');

INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('gbravo');
INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('ottoman69');
INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('genericUser');


INSERT INTO EQUIVALENCIASINGREDIENTE(RESTAURANTE_NOMBRE, INGREDIENTE_NOMBRE, EQUIVALENCIA) VALUES ('CREPES Y WAFFLES', 'NUTELLA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'AZUCAR', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'HELADO DE VAINILLA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'LECHUGA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAPA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'HELADO DE VAINILLA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'AZUCAR', 1);

INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO CORRAL', 1, 30000, 15000, 'HAMBURGUESAS', 20, 'CORRAL');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('CORRIENTAZO', 2, 10000, 5000, 'CASERO', 5, 'RESTAURANTE DE LOS ALPES');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO WAFFLE', 1, 40000, 1000, 'POSTRES', 15, 'CREPES Y WAFFLES');

INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'CHURRASCO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'GASEOSA');

INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'WAFFLE DE NUTELLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'CHURRASCO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS');

INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'RES');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAPA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'PAPA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'AZUCAR');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'NUTELLA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'HELADO DE VAINILLA');


INSERT INTO EQUIVALENCIASPRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE, EQUIVALENCIA) VALUES ('CORRAL', 'PAPAS FRITAS', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CORRAL', 'GASEOSA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CORRAL', 'MALTEADA DE VAINILLA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'CHURRASCO', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'GASEOSA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'GASEOSA', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'MALTEADA DE VAINILLA', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'WAFFLE DE NUTELLA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'HELADO DE VAINILLA', 2);

INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'PAN', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'LECHUGA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'NUTELLA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'AZUCAR', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAPA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'LECHUGA', 1);

INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CHATARRA', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('HAMBURGUESAS', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('SABROSO', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CARNE', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('ASADO', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('DULCE', 'WAFFLE DE NUTELLA');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('POSTRE', 'WAFFLE DE NUTELLA');

INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 2, 'COMBO CORRAL', 'gbravo', 'BOSQUE');
INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 1, 'COMBO WAFFLE', 'genericUser', 'PLAYA BRISA Y MAR');
INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 3, 'COMBO WAFFLE', 'ottoman69', 'GRANJA');

INSERT INTO MENU_CHECKOUT VALUES (1, 'COMBO CORRAL', 3);
INSERT INTO MENU_CHECKOUT VALUES (2, 'COMBO CORRAL', 1);
INSERT INTO MENU_CHECKOUT VALUES (2, 'COMBO WAFFLE', 2);
INSERT INTO MENU_CHECKOUT VALUES (3, 'CORRIENTAZO', 5);

--FIN :)