CREATE TABLE RESTAURANTE(
    NOMBRE VARCHAR(35),
    DESCRIPCION VARCHAR(280),
    TIPOCOMIDAREST VARCHAR(15),
    PAGINAWEB VARCHAR(50),
    CONSTRAINT nom_rest_pk PRIMARY KEY (NOMBRE));
    
CREATE TABLE INVENTARIO(
    RESTAURANTE_NOMBRE VARCHAR2(35),
    CONSTRAINT inv_nom_pk PRIMARY KEY(RESTAURANTE_NOMBRE),
    CONSTRAINT inv_nom_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));

    
CREATE TABLE PRODUCTO(
    NOMBRE VARCHAR2(25),
    CATEGORIA NUMBER(8),
    PRECIOVENTA NUMBER(18),
    COSTOPRODUCCION NUMBER(17),
    TIPOCOMIDAPROD VARCHAR2(20),
    TIEMPOPREPARACION NUMBER(7),
    CONSTRAINT pro_pk PRIMARY KEY (NOMBRE));

CREATE TABLE PRODUCTOSBODEGA(
    CANTIDADPRODUCTO NUMBER(10),
    INVENTARIO_RESTAURANTE_NOMBRE VARCHAR2(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT prodbod_pk PRIMARY KEY(INVENTARIO_RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT prodbod_inv_fk
        FOREIGN KEY (INVENTARIO_RESTAURANTE_NOMBRE)
        REFERENCES INVENTARIO(RESTAURANTE_NOMBRE),
    CONSTRAINT prodbod_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE) );

CREATE TABLE EQUIVALENCIASPRODUCTO(
    RESTAURANTE_NOMBRE VARCHAR2(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT eqPROD_PK PRIMARY KEY (RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT eqPROD_PROD_FK
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT eqPROD_REST_FK
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));
    
CREATE TABLE INGREDIENTE(
    NOMBRE VARCHAR2(30),
    DESCESP VARCHAR2(300),
    DESCING VARCHAR2(300),
    TIPO VARCHAR(15),
    CONSTRAINT ing_PK PRIMARY KEY (NOMBRE));
        
CREATE TABLE PRODUCTO_INGREDIENTE(
    INGREDIENTE_NOMBRE VARCHAR(30),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT proding_pk PRIMARY KEY (INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE),
    CONSTRAINT proding_ing_fk
        FOREIGN KEY (INGREDIENTE_NOMBRE)
        REFERENCES INGREDIENTE(NOMBRE),
    CONSTRAINT proding_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE) );
                     
CREATE TABLE EQUIVALENCIASINGREDIENTE(
    INGREDIENTE_NOMBRE VARCHAR2(30),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT eqingr_PK PRIMARY KEY (INGREDIENTE_NOMBRE,RESTAURANTE_NOMBRE),
    CONSTRAINT eqingr_INGR_FK
        FOREIGN KEY (INGREDIENTE_NOMBRE)
        REFERENCES INGREDIENTE(NOMBRE),
    CONSTRAINT eqINGR_REST_FK
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));
        

CREATE TABLE MENU(
    NOMBRE VARCHAR2(25),
    CATEGORIA NUMBER(8),
    PRECIOVENTA NUMBER(18),
    COSTOPRODUCCION NUMBER(17),
    TIPOCOMIDAPROD VARCHAR2(20),
    TIEMPOPREPARACION NUMBER(7),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT menu_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT menu_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));

CREATE TABLE CLIENTESREGISTRADOS(
    USUARIO VARCHAR(30),
    CONTRASEÑA VARCHAR(30),
    ROL VARCHAR(30),
    CORREO VARCHAR(40),
    CONSTRAINT CLI_pk PRIMARY KEY (USUARIO));
    
CREATE TABLE ZONA(
    NOMBRE VARCHAR(30),
    CAPACIDAD NUMBER(8),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT zona_pk PRIMARY KEY (NOMBRE),
    CONSTRAINT zona_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));

CREATE TABLE EVENTO(
    ID NUMBER(30),
    MENU_NOMBRE VARCHAR(25),
    CLIENTESREGISTRADOS_USUARIO VARCHAR(30),
    ZONA_NOMBRE VARCHAR(30),
    CONSTRAINT evento_pk PRIMARY KEY (ID),
    CONSTRAINT evento_menu_fk
        FOREIGN KEY(MENU_NOMBRE)
        REFERENCES MENU(NOMBRE),
    CONSTRAINT evento_cli_fk
        FOREIGN KEY(CLIENTESREGISTRADOS_USUARIO)
        REFERENCES CLIENTESREGISTRADOS(USUARIO),
    CONSTRAINT evento_zon_fk
        FOREIGN KEY(ZONA_NOMBRE)
        REFERENCES ZONA(NOMBRE));
        

    
CREATE TABLE RESTAURANTE_PRODUCTO(
    RESTAURANTE_NOMBRE VARCHAR(35),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT rest_prod_pk PRIMARY KEY (RESTAURANTE_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT rest_prod_rest_fk
        FOREIGN KEY(RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE),
    CONSTRAINT rest_prod_PROD_fk
        FOREIGN KEY(PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE));

CREATE TABLE PRODUCTO_MENU(
    MENU_NOMBRE VARCHAR(25),
    PRODUCTO_NOMBRE VARCHAR(25),
    CONSTRAINT prod_menu_pk PRIMARY KEY (MENU_NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT prod_menu_menu_fk
        FOREIGN KEY(MENU_NOMBRE)
        REFERENCES MENU(NOMBRE),
    CONSTRAINT prod_menu_prod_fk
        FOREIGN KEY(PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE));
        


    
CREATE TABLE TIPOCOMIDA(
    NOMBRE VARCHAR2(25),
    PRODUCTO_NOMBRE VARCHAR2(25),
    CONSTRAINT TIPOCOMIDA_pk PRIMARY KEY(NOMBRE,PRODUCTO_NOMBRE),
    CONSTRAINT TIPOCOMIDA_PROD_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE));



CREATE TABLE REPRESENTANTE(
    NOMBRE VARCHAR(30),
    CELULAR VARCHAR(10),
    RESTAURANTE_NOMBRE VARCHAR(35),
    CONSTRAINT rep_pk PRIMARY KEY(NOMBRE),
    CONSTRAINT rep_rest_fk
        FOREIGN KEY (RESTAURANTE_NOMBRE)
        REFERENCES RESTAURANTE(NOMBRE));

CREATE TABLE CHECKOUT(
    ID NUMBER(20),
    ENTREGADO NUMBER(1),
    TIEMPOR VARCHAR(15),
    ZONA_NOMBRE VARCHAR(30),
    CONSTRAINT checkout_pk PRIMARY KEY (ID),
    CONSTRAINT ck_zona_fk
        FOREIGN KEY (ZONA_NOMBRE)
        REFERENCES ZONA(NOMBRE));

CREATE TABLE PRODUCTO_CHECKOUT(
    CHECKOUT_ID NUMBER(20),
    PRODUCTO_NOMBRE VARCHAR(25),
    CANTIDAD_PRODUCTO NUMBER(5),
    CONSTRAINT prod_ck_pk PRIMARY KEY(CHECKOUT_ID,PRODUCTO_NOMBRE),
    CONSTRAINT prod_ck_ck_fk
        FOREIGN KEY (CHECKOUT_ID)
        REFERENCES CHECKOUT(ID),
    CONSTRAINT prod_ck_prod_fk
        FOREIGN KEY (PRODUCTO_NOMBRE)
        REFERENCES PRODUCTO(NOMBRE),
    CONSTRAINT prod_ck_chk CHECK (CANTIDAD_PRODUCTO>0));
