
SELECT DISTINCT us.* 
FROM USUARIO us INNER JOIN CHECKOUT ck ON ck.USUARIO_CLIENTE=us.USUARIO WHERE us.USUARIO NOT IN (SELECT DISTINCT USUARIO_CLIENTE
    FROM PRODUCTO_CHECKOUT INNER JOIN CHECKOUT ON PRODUCTO_CHECKOUT.CHECKOUT_ID = CHECKOUT.ID
    WHERE RESTAURANTE_NOMBRE='El Corral' AND CHECKOUT.TIEMPOR BETWEEN '01/11/2017' AND '20/11/2017') AND ck.TIEMPOR BETWEEN '01/11/2017' AND '20/11/2017';

CREATE INDEX uno
ON CHECKOUT (USUARIO_CLIENTE,  ID);

CREATE INDEX dos
ON PRODUCTO_CHECKOUT(CHECKOUT_ID);

SELECT DISTINCT us.* 
FROM USUARIO us INNER JOIN (SELECT * 
  FROM PRODUCTO_CHECKOUT INNER JOIN CHECKOUT ON PRODUCTO_CHECKOUT.CHECKOUT_ID = CHECKOUT.ID
    WHERE CHECKOUT.TIEMPOR BETWEEN '01/11/2017' AND '20/11/2017') ck
ON ck.USUARIO_CLIENTE=us.USUARIO WHERE ck.RESTAURANTE_NOMBRE!='El Corral';

SELECT DISTINCT US.* 
FROM (SELECT DISTINCT CHECKOUT.USUARIO_CLIENTE
    FROM PRODUCTO_CHECKOUT INNER JOIN CHECKOUT ON PRODUCTO_CHECKOUT.CHECKOUT_ID = CHECKOUT.ID
    WHERE RESTAURANTE_NOMBRE='El Corral' AND CHECKOUT.TIEMPOR BETWEEN '01/11/2017' AND '20/11/2017')T1
INNER JOIN USUARIO US ON T1.USUARIO_CLIENTE=US.USUARIO;
