INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CORRAL', 'HAMBURGUESAS EL CORRRAL, LA RECETA ORIGINAL', 'HAMBURGUESAS', 'http://elcorral.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CREPES Y WAFFLES', 'TORTILLAS DULCES Y SALDAS COLOMBIANAS', 'MIXTO', 'http://crepesandwaffles.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('RESTAURANTE DE LOS ALPES', 'RESTAURANTE MIXTO', 'MIXTO', 'http://restaurante.unialpes.blogspot.co');

INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Pepito P�rez', '6666666666', 'RESTAURANTE DE LOS ALPES');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Ana Lisa Melo', '0123456789', 'CORRAL');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Elver Galarga', '9876543210', 'CREPES Y WAFFLES');

INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CORRAL');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CREPES Y WAFFLES');


INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CORRALISIMA TODOTERRENO', 1, 20000, 10, 'HAMBURGUESA', 15 );
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('WAFFLE DE NUTELLA', 2, 17000, 3000, 'WAFFLE', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('HELADO DE VAINILLA', 2, 8000, 5000, 'ELAOU', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('MALTEADA DE VAINILLA', 3, 6000, 1000, 'BEBIDA', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('PAPAS FRITAS', 4, 4000, 3000, 'ACOMPAnAMIENTO', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CHURRASCO', 5, 3000, 500, 'PLATO FUERTE', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('GASEOSA', 3, 3000, 1000, 'BEBIDA',2);

INSERT INTO PRODUCTOSBODEGA VALUES (69, 'RESTAURANTE DE LOS ALPES', 'GASEOSA', 100);
INSERT INTO PRODUCTOSBODEGA VALUES (51, 'RESTAURANTE DE LOS ALPES', 'CHURRASCO', 80);
INSERT INTO PRODUCTOSBODEGA VALUES (72, 'RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS', 90);
INSERT INTO PRODUCTOSBODEGA VALUES (83, 'CREPES Y WAFFLES', 'GASEOSA', 85);
INSERT INTO PRODUCTOSBODEGA VALUES (120, 'CREPES Y WAFFLES', 'MALTEADA DE VAINILLA', 150);
INSERT INTO PRODUCTOSBODEGA VALUES (83, 'CORRAL', 'GASEOSA', 100);
INSERT INTO PRODUCTOSBODEGA VALUES (68, 'CORRAL', 'MALTEADA DE VAINILLA', 90);
INSERT INTO PRODUCTOSBODEGA VALUES (37, 'CORRAL', 'CORRALISIMA TODOTERRENO', 50);
INSERT INTO PRODUCTOSBODEGA VALUES (56, 'CORRAL', 'PAPAS FRITAS', 70);

INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('RES', 'DE LA VACA', 'FROM THE COW', 'CARNE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAPA', 'DE LA TIERRA', 'FROM THE EARTH', 'PAPA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('WAFFLE', 'DE HARINA', 'FLOUR', 'WAFFLE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('NUTELLA', 'DE AVELLANAS', 'AVELLANEITON', 'SALSA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('AZUCAR', 'DE CAnA', 'FROM MATA', 'CANCER');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('HELADO DE VAINILLA', 'DE VAINILLA', 'FROM VACA', 'HELAO');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAN', 'DE TRIGO', 'WHEAT', 'PAN');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('LECHUGA', 'VEGANA', 'VEGAN', 'FITNESS');

INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('AZUCAR', 'GASEOSA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAPA', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAN', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('HELADO DE VAINILLA', 'MALTEADA DE VAINILLA');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('BOSQUE', 67, 'CREPES Y WAFFLES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('PLAYA BRISA Y MAR', 78, 'RESTAURANTE DE LOS ALPES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('GRANJA', 78, 'CORRAL');

INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (1, 1, 1501766720000, 'BOSQUE');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (2, 0, 1502371520000, 'PLAYA BRISA Y MAR');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (3, 1, 1499693120000, 'GRANJA');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (5, 1, 1499703406000, 'BOSQUE');
INSERT INTO CHECKOUT(ID, ENTREGADO, TIEMPOR, ZONA_NOMBRE) VALUES (4, 0, 1494436606000, 'PLAYA BRISA Y MAR');

INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (1, 'MALTEADA DE VAINILLA', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (2, 'CHURRASCO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'CORRALISIMA TODOTERRENO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'PAPAS FRITAS', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (3, 'GASEOSA', 3);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (4, 'CHURRASCO', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (4, 'GASEOSA', 2);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (5, 'WAFFLE DE NUTELLA', 1);
INSERT INTO PRODUCTO_CHECKOUT(CHECKOUT_ID, PRODUCTO_NOMBRE, CANTIDAD_PRODUCTO) VALUES (5, 'GASEOSA', 1);


INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('genericUser', 'Omaewamoushindeiru', 'cliente', 'abc@gmail.com');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('ottoman69', 'Nani?1234', 'cliente', 'gbravo@uniandes.edu.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('juan10', 'claveGenerica', 'admin restaurante', 'juan1650@hotmail.com');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('gbravo', '5 pa todos', 'cliente', 'gbravo@uniandes.edu.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('DB_MANAGER_rotonda', 'clavedificilysecreta', 'admin DB', 'db@rotondAndes.co');
INSERT INTO USUARIO(USUARIO, CONTRASENA,ROL, CORREO) VALUES ('harryPotter', 'huerfanoxdxdxd', 'gerente', 'hp@howards.edu.xy');

INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('gbravo');
INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('ottoman69');
INSERT INTO CLIENTESREGISTRADOS(USUARIO_CLIENTE) VALUES ('genericUser');

INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO CORRAL', 1, 30000, 15000, 'HAMBURGUESAS', 20, 'CORRAL');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('CORRIENTAZO', 2, 10000, 5000, 'CASERO', 5, 'RESTAURANTE DE LOS ALPES');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO WAFFLE', 1, 40000, 1000, 'POSTRES', 15, 'CREPES Y WAFFLES');

INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'CHURRASCO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'GASEOSA');

INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'WAFFLE DE NUTELLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'CHURRASCO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS');

INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'RES');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAPA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'PAPA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CORRAL', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'LECHUGA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'PAN');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'AZUCAR');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'NUTELLA');
INSERT INTO RESTAURANTE_INGREDIENTE VALUES ('CREPES Y WAFFLES', 'HELADO DE VAINILLA');


INSERT INTO EQUIVALENCIASPRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE, EQUIVALENCIA) VALUES ('CORRAL', 'PAPAS FRITAS', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CORRAL', 'GASEOSA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CORRAL', 'MALTEADA DE VAINILLA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'CHURRASCO', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('RESTAURANTE DE LOS ALPES', 'GASEOSA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'GASEOSA', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'MALTEADA DE VAINILLA', 1);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'WAFFLE DE NUTELLA', 2);
INSERT INTO EQUIVALENCIASPRODUCTO VALUES ('CREPES Y WAFFLES', 'HELADO DE VAINILLA', 2);

INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'PAN', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CORRAL', 'LECHUGA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'NUTELLA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('CREPES Y WAFFLES', 'AZUCAR', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'PAPA', 1);
INSERT INTO EQUIVALENCIASINGREDIENTE VALUES ('RESTAURANTE DE LOS ALPES', 'LECHUGA', 1);

INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CHATARRA', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('HAMBURGUESAS', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('SABROSO', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CARNE', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('ASADO', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('DULCE', 'WAFFLE DE NUTELLA');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('POSTRE', 'WAFFLE DE NUTELLA');

INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 2, 'COMBO CORRAL', 'gbravo', 'BOSQUE');
INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 1, 'COMBO WAFFLE', 'genericUser', 'PLAYA BRISA Y MAR');
INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIREGS_USUARIO_CLIENTE, ZONA_NOMBRE) VALUES( 3, 'COMBO WAFFLE', 'ottoman69', 'GRANJA');

INSERT INTO MENU_CHECKOUT VALUES (1, 'COMBO CORRAL', 3);
INSERT INTO MENU_CHECKOUT VALUES (2, 'COMBO CORRAL', 1);
INSERT INTO MENU_CHECKOUT VALUES (2, 'COMBO WAFFLE', 2);
INSERT INTO MENU_CHECKOUT VALUES (3, 'CORRIENTAZO', 5);