INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CORRAL', 'HAMBURGUESAS EL CORRRAL, LA RECETA ORIGINAL', 'HAMBURGUESAS', 'http://elcorral.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('CREPES Y WAFFLES', 'TORTILLAS DULCES Y SALDAS COLOMBIANAS', 'MIXTO', 'http://crepesandwaffles.com.co');
INSERT INTO RESTAURANTE(NOMBRE, DESCRIPCION, TIPOCOMIDAREST, PAGINAWEB) values ('RESTAURANTE DE LOS ALPES', 'RESTAURANTE MIXTO', 'MIXTO', 'http://restaurante.unialpes.blogspot.co');

INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Pepito Pérez', '6666666666', 'RESTAURANTE DE LOS ALPES');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Ana Lisa Melo', '0123456789', 'CORRAL');
INSERT INTO REPRESENTANTE(NOMBRE, CELULAR, RESTAURANTE_NOMBRE) VALUES ('Elver Galarga', '9876543210', 'CREPES Y WAFFLES');

INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CORRAL');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES');
INSERT INTO INVENTARIO(RESTAURANTE_NOMBRE) VALUES ('CREPES Y WAFFLES');


INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CORRALISIMA TODOTERRENO', 1, 20000, 10, 'HAMBURGUESA', 15 );
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('WAFFLE DE NUTELLA', 2, 17000, 10000, 'WAFFLE', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('MALTEADA DE VAINILLA', 3, 6000, 1000, 'BEBIDA', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('PAPAS FRITAS', 4, 4000, 3000, 'ACOMPAÑAMIENTO', 5);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('CHURRASCO', 5, 3000, 500, 'PLATO FUERTE', 15);
INSERT INTO PRODUCTO(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION) VALUES ('GASEOSA', 3, 3000, 1000, 'BEBIDA',2);

INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'CHURRASCO');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (69, 'RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (223, 'CREPES Y WAFFLES', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (223, 'CREPES Y WAFFLES', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'GASEOSA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTOSBODEGA(CANTIDADPRODUCTO, INVENTARIO_RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES (345, 'CORRAL', 'PAPAS FRITAS');

INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('RES', 'DE LA VACA', 'FROM THE COW', 'CARNE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAPA', 'DE LA TIERRA', 'FROM THE EARTH', 'PAPA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('WAFFLE', 'DE HARINA', 'FLOUR', 'WAFFLE');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('NUTELLA', 'DE AVELLANAS', 'AVELLANEITON', 'SALSA');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('AZUCAR', 'DE CAÑA', 'FROM MATA', 'CANCER');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('HELADO DE VAINILLA', 'DE VAINILLA', 'FROM VACA', 'HELAO');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('PAN', 'DE TRIGO', 'WHEAT', 'PAN');
INSERT INTO INGREDIENTE(NOMBRE, DESCESP, DESCING, TIPO) VALUES ('LECHUGA', 'VEGANA', 'VEGAN', 'FITNESS');

INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RES', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('AZUCAR', 'GASEOSA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAPA', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('PAN', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('LECHUGA', 'CHURRASCO');
INSERT INTO PRODUCTO_INGREDIENTE(INGREDIENTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('HELADO DE VAINILLA', 'MALTEADA DE VAINILLA');

INSERT INTO CHECKOUT(ID, ENTREGADO) VALUES (1, 1);
INSERT INTO CHECKOUT(ID, ENTREGADO) VALUES (2, 0);
INSERT INTO CHECKOUT(ID, ENTREGADO) VALUES (3, 1);
INSERT INTO CHECKOUT(ID, ENTREGADO) VALUES (5, 1);
INSERT INTO CHECKOUT(ID, ENTREGADO) VALUES (4, 0);

INSERT INTO CLIENTESREGISTRADOS(USUARIO, CONTRASEÑA,ROL, CORREO) VALUES ('suTioNecio', 'nepe', 'comensal', 'suTioLoToca@gmail.com');
INSERT INTO CLIENTESREGISTRADOS(USUARIO, CONTRASEÑA,ROL, CORREO) VALUES ('gloria1', 'rio', 'admin restaurante', 'gloriaMetrocable@hotmail.com');
INSERT INTO CLIENTESREGISTRADOS(USUARIO, CONTRASEÑA,ROL, CORREO) VALUES ('german', '5 pa todos', 'comensal', 'gbravo@uniandes.edu.co');
INSERT INTO CLIENTESREGISTRADOS(USUARIO, CONTRASEÑA,ROL, CORREO) VALUES ('harryPotter', 'huerfanoxdxdxd', 'gerente', 'hp@howards.edu.magia');


INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('NUTELLA', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('AZUCAR', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('WAFFLE', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('HELADO DE VAINILLA', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('LECHUGA', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('PAPA', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('AZUCAR', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('HELADO DE VAINILLA', 'CORRAL');
INSERT INTO EQUIVALENCIASINGREDIENTE(INGREDIENTE_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('AZUCAR', 'CORRAL');

INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO CORRAL', 1, 30000, 15000, 'HAMBURGUESAS', 20, 'CORRAL');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('CORRIENTAZO', 2, 10000, 5000, 'CASERO', 5, 'RESTAURANTE DE LOS ALPES');
INSERT INTO MENU(NOMBRE, CATEGORIA, PRECIOVENTA, COSTOPRODUCCION, TIPOCOMIDAPROD, TIEMPOPREPARACION, RESTAURANTE_NOMBRE) VALUES ('COMBO WAFFLE', 1, 40000, 1000, 'POSTRES', 15, 'CREPES Y WAFFLES');

INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'WAFFLE DE NUTELLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'GASEOSA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('COMBO WAFFLE', 'MALTEADA DE VAINILLA');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'CHURRASCO');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'PAPAS FRITAS');
INSERT INTO PRODUCTO_MENU(MENU_NOMBRE, PRODUCTO_NOMBRE) VALUES('CORRIENTAZO', 'GASEOSA');

INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'CORRALISIMA TODOTERRENO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CORRAL', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'WAFFLE DE NUTELLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('CREPES Y WAFFLES', 'MALTEADA DE VAINILLA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'GASEOSA');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'CHURRASCO');
INSERT INTO RESTAURANTE_PRODUCTO(RESTAURANTE_NOMBRE, PRODUCTO_NOMBRE) VALUES ('RESTAURANTE DE LOS ALPES', 'PAPAS FRITAS');

INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('CORRALISIMA TODOTERRENO', 'CORRAL');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('GASEOSA', 'CORRAL');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('PAPAS FRITAS', 'CORRAL');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('CHURRASCO', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('PAPAS FRITAS', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('GASEOSA', 'RESTAURANTE DE LOS ALPES');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('GASEOSA', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('MALTEADA DE VAINILLA', 'CREPES Y WAFFLES');
INSERT INTO EQUIVALENCIASPRODUCTO(PRODUCTO_NOMBRE, RESTAURANTE_NOMBRE) VALUES ('WAFFLE DE NUTELLA', 'CREPES Y WAFFLES');

INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CHATARRA', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('HAMBURGUESAS', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('SABROSO', 'CORRALISIMA TODOTERRENO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('CARNE', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('ASADO', 'CHURRASCO');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('DULCE', 'WAFFLE DE NUTELLA');
INSERT INTO TIPOCOMIDA(NOMBRE, PRODUCTO_NOMBRE) VALUES ('POSTRE', 'WAFFLE DE NUTELLA');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('BOSQUE', 67, 'CREPES Y WAFFLES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('PLAYA BRISA Y MAR', 78, 'RESTAURANTE DE LOS ALPES');
INSERT INTO ZONA (NOMBRE, CAPACIDAD, RESTAURANTE_NOMBRE) VALUES ('GRANJA', 78, 'CORRAL');

INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIENTESREGISTRADOS_USUARIO, ZONA_NOMBRE) VALUES( 123, 'COMBO CORRAL', 'german', 'BOSQUE');
INSERT INTO EVENTO(ID, MENU_NOMBRE, CLIENTESREGISTRADOS_USUARIO, ZONA_NOMBRE) VALUES( 1, 'COMBO WAFFLE', 'gloria1', 'PLAYA BRISA Y MAR');
